# Generated by Django 5.1.4 on 2025-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nome_requisitante',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
