# Generated by Django 5.1.4 on 2025-09-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_nome_requisitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='precisa_alterar_senha',
            field=models.BooleanField(default=True, help_text='Usuário precisa alterar senha no primeiro login'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='senha_alterada_em',
            field=models.DateTimeField(blank=True, help_text='Data da última alteração de senha', null=True),
        ),
    ]
