# Generated by Django 5.1.4 on 2025-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_precisa_alterar_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('REQUISITANTE', 'Requisitante'), ('TRANSPORTES', 'Setor de Transportes')], default='REQUISITANTE', max_length=20),
        ),
    ]
