# Generated by Django 5.1.4 on 2025-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('REQUISITANTE', 'Requisitante'), ('SUPERVISOR', 'Supervisor'), ('TRANSPORTES', 'Setor de Transportes')], default='REQUISITANTE', max_length=20),
        ),
    ]
