# Generated by Django 5.1.4 on 2025-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude da localização atual', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude da localização atual', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='precisao_gps',
            field=models.FloatField(blank=True, help_text='Precisão do GPS em metros', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='status_online',
            field=models.BooleanField(default=False, help_text='Usuário está online e compartilhando localização'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_localizacao',
            field=models.DateTimeField(blank=True, help_text='Última vez que a localização foi atualizada', null=True),
        ),
    ]
