# Generated by Django 5.1.4 on 2025-09-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfilusuario_latitude_perfilusuario_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('REQUISITANTE', 'Requisitante'), ('TRANSPORTES', 'Setor de Transportes')], default='REQUISITANTE', max_length=20),
        ),
    ]
