# Generated by Django 5.1.4 on 2025-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status_operacional',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo')], default='OPERACIONAL', help_text='Status operacional do equipamento', max_length=20),
        ),
    ]
