# Generated by Django 5.1.4 on 2025-09-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipamento_status_operacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='categoria',
            field=models.CharField(choices=[('TRATOR', 'Trator'), ('PRANCHA_REBOQUE', 'Prancha Reboque'), ('EMPILHADEIRA', 'Empilhadeira'), ('CAMINHAO_MUNCK', 'Caminhão Munck'), ('CARRETA_HIDRAULICA', 'Carreta Hidráulica'), ('GUINDASTE_RODOVIARIO', 'Guindaste Rodoviário'), ('CAVALO_MECANICO', 'Cavalo Mecânico'), ('OUTROS', 'Outros')], default='MATERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('REQUISITANTE', 'Requisitante'), ('DEMANDANTE', 'Demandante'), ('TRANSPORTES', 'Setor de Transportes')], default='REQUISITANTE', max_length=20),
        ),
    ]
