# Generated by Django 5.1.4 on 2025-09-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_update_equipamento_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do local de trabalho', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do local')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude do local', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude do local', max_digits=11)),
                ('raio_metros', models.IntegerField(default=50, help_text='Raio de tolerância em metros')),
                ('ativo', models.BooleanField(default=True, help_text='Local está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Local de Trabalho',
                'verbose_name_plural': 'Locais de Trabalho',
            },
        ),
    ]
