# Generated by Django 4.2.16 on 2025-09-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_localtrabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('DEMANDANTE', 'Demandante'), ('TRANSPORTES', 'Setor de Transportes')], default='DEMANDANTE', max_length=20),
        ),
    ]
