# Generated by Django 4.2.16 on 2025-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_requisitante_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='foto_comprovacao',
            field=models.ImageField(blank=True, help_text='Foto para comprovar a conclusão do serviço', null=True, upload_to='comprovacoes/'),
        ),
    ]
