# Generated by Django 4.2.16 on 2025-10-07 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_add_foto_comprovacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade_total', models.DecimalField(decimal_places=2, default=15000.0, help_text='Capacidade total do tanque em litros', max_digits=10)),
                ('nivel_atual', models.DecimalField(decimal_places=2, default=15000.0, help_text='Nível atual de diesel no tanque', max_digits=10)),
                ('nivel_alerta', models.DecimalField(decimal_places=2, default=5000.0, help_text='Nível de alerta (amarelo) em litros', max_digits=10)),
                ('nivel_critico', models.DecimalField(decimal_places=2, default=2000.0, help_text='Nível crítico (vermelho) em litros', max_digits=10)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuração do Tanque',
                'verbose_name_plural': 'Configurações do Tanque',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome/identificação do veículo', max_length=200)),
                ('placa', models.CharField(help_text='Placa do veículo', max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('CAMINHAO', 'Caminhão'), ('CARRETA', 'Carreta'), ('TRATOR', 'Trator'), ('EMPILHADEIRA', 'Empilhadeira'), ('MUNCK', 'Munck'), ('GUINDASTE', 'Guindaste'), ('OUTROS', 'Outros')], default='CAMINHAO', max_length=20)),
                ('modelo', models.CharField(blank=True, help_text='Modelo do veículo', max_length=100)),
                ('ano', models.IntegerField(blank=True, help_text='Ano de fabricação', null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('tem_agenda', models.BooleanField(default=True, help_text='Aparece no agendamento de pedidos')),
                ('capacidade_tanque', models.DecimalField(decimal_places=2, default=200.0, help_text='Capacidade do tanque do veículo em litros', max_digits=8)),
                ('consumo_medio', models.DecimalField(blank=True, decimal_places=2, help_text='Consumo médio em km/litro', max_digits=5, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AbastecimentoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade_litros', models.DecimalField(decimal_places=2, help_text='Quantidade de litros abastecida', max_digits=8)),
                ('odometro_atual', models.IntegerField(blank=True, help_text='Quilometragem atual do veículo', null=True)),
                ('odometro_anterior', models.IntegerField(blank=True, help_text='Quilometragem anterior (calculado automaticamente)', null=True)),
                ('km_rodados', models.IntegerField(blank=True, help_text='Quilômetros rodados desde o último abastecimento', null=True)),
                ('consumo_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Consumo calculado em km/litro', max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o abastecimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(help_text='Usuário que fez o abastecimento', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='core.veiculo')),
            ],
            options={
                'verbose_name': 'Abastecimento de Veículo',
                'verbose_name_plural': 'Abastecimentos de Veículos',
                'ordering': ['-data_abastecimento'],
            },
        ),
    ]
