# Generated by Django 4.2.16 on 2025-10-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_controle_diesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimentoveiculo',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente relacionado ao abastecimento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
    ]
