# Generated by Django 4.2.16 on 2025-10-07 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_add_cliente_abastecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbastecimentoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, help_text='Quantidade de diesel recebida em litros', max_digits=10)),
                ('valor_por_litro', models.DecimalField(decimal_places=4, help_text='Valor pago por litro (R$)', max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total da compra (R$)', max_digits=12)),
                ('data_chegada', models.DateTimeField(help_text='Data e hora da chegada do diesel')),
                ('fornecedor', models.CharField(blank=True, help_text='Nome do fornecedor', max_length=200)),
                ('numero_nota_fiscal', models.CharField(blank=True, help_text='Número da nota fiscal', max_length=50)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o abastecimento')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('nivel_anterior', models.DecimalField(decimal_places=2, help_text='Nível do tanque antes do abastecimento', max_digits=10)),
                ('nivel_posterior', models.DecimalField(decimal_places=2, help_text='Nível do tanque após o abastecimento', max_digits=10)),
                ('operador', models.ForeignKey(help_text='Usuário que registrou a chegada', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abastecimento do Tanque',
                'verbose_name_plural': 'Abastecimentos do Tanque',
                'ordering': ['-data_chegada'],
            },
        ),
    ]
