# Generated by Django 4.2.16 on 2025-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_abastecimentotanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotanque',
            name='capacidade_extra',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Capacidade do tanque extra para recebimento', max_digits=10),
        ),
    ]
