# Generated by Django 4.2.16 on 2025-10-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configuracaotanque_capacidade_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDiesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinatario', models.EmailField(help_text='Email que receberá os alertas', max_length=254)),
                ('nome_destinatario', models.CharField(help_text='Nome do destinatário', max_length=100)),
                ('ativo', models.BooleanField(default=True, help_text='Se deve receber alertas')),
                ('alerta_critico', models.BooleanField(default=True, help_text='Receber alerta de nível crítico')),
                ('alerta_alerta', models.BooleanField(default=True, help_text='Receber alerta de nível de atenção')),
                ('ultimo_alerta_critico', models.DateTimeField(blank=True, help_text='Último alerta crítico enviado', null=True)),
                ('ultimo_alerta_alerta', models.DateTimeField(blank=True, help_text='Último alerta de atenção enviado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta de Diesel',
                'verbose_name_plural': 'Alertas de Diesel',
                'ordering': ['nome_destinatario'],
            },
        ),
    ]
