# Generated by Django 4.2.16 on 2025-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alertadiesel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='primary', help_text='Cor do badge (primary, success, warning, danger, info, secondary, dark)', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Equipamento',
                'verbose_name_plural': 'Categorias de Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='em_servico',
            field=models.BooleanField(default=True, help_text='Equipamento está em serviço ou fora de serviço'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tem_agenda',
            field=models.BooleanField(default=True, help_text='Se marcado, o veículo aparecerá nas opções de agendamento de pedidos', verbose_name='Com Agenda'),
        ),
    ]
