# Generated by Django 4.2.16 on 2025-10-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_categoriaequipamento_equipamento_em_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('DEMANDANTE', 'Demandante'), ('TRANSPORTES', 'Setor de Transportes'), ('MANUTENCAO', 'Manutenção')], default='DEMANDANTE', max_length=20),
        ),
    ]
