# Generated by Django 5.1.4 on 2025-10-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alterar_abastecimento_para_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='quantidade_litros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade de litros que o equipamento pode armazenar ou consumir', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='abastecimentoveiculo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='core.veiculo'),
        ),
    ]
