# Generated by Django 4.2.16 on 2025-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_equipamento_quantidade_litros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('DEMANDANTE', 'Demandante'), ('TRANSPORTES', 'Setor de Transportes'), ('MANUTENCAO_PTA', 'Manutenção - PTA (Ponte de Transferência)'), ('MANUTENCAO_EMPILHADEIRA', 'Manutenção - Empilhadeiras'), ('MANUTENCAO_GUINDASTE', 'Manutenção - Guindastes'), ('MANUTENCAO_SOLDA', 'Manutenção - Equipamentos de Solda'), ('MANUTENCAO_GERAL', 'Manutenção - Equipamentos Gerais'), ('TERCEIRO_MANUTENCAO_PTA', 'Terceiro - Manutenção PTA'), ('TERCEIRO_MANUTENCAO_EMPILHADEIRA', 'Terceiro - Manutenção Empilhadeiras'), ('TERCEIRO_MANUTENCAO_GUINDASTE', 'Terceiro - Manutenção Guindastes'), ('TERCEIRO_MANUTENCAO_SOLDA', 'Terceiro - Manutenção Solda'), ('TERCEIRO_MANUTENCAO_GERAL', 'Terceiro - Manutenção Geral'), ('MANUTENCAO', 'Manutenção (Genérica)')], default='DEMANDANTE', max_length=50),
        ),
    ]
