# Generated by Django 4.2.16 on 2025-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_perfil', models.CharField(help_text='Código do perfil (deve corresponder a um PERFIL_CHOICES)', max_length=50, unique=True)),
                ('nome_personalizado', models.CharField(blank=True, help_text='Nome personalizado para o perfil', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do perfil')),
                ('permissoes_resumo', models.TextField(blank=True, help_text='Resumo das permissões do perfil')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Descrição de Perfil',
                'verbose_name_plural': 'Descrições de Perfis',
                'ordering': ['codigo_perfil'],
            },
        ),
    ]
