# Generated by Django 4.2.16 on 2025-12-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_descricaoperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da empresa', max_length=200, unique=True)),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ da empresa (formato: 00.000.000/0000-00)', max_length=18)),
                ('contrato', models.CharField(blank=True, help_text='Número do contrato', max_length=100)),
                ('tipo', models.CharField(choices=[('PROPRIA', 'Empresa Própria'), ('TERCEIRIZADA', 'Empresa Terceirizada')], default='TERCEIRIZADA', help_text='Tipo da empresa', max_length=20)),
                ('contato', models.CharField(blank=True, help_text='Nome do contato principal', max_length=100)),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato', max_length=254)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a empresa')),
                ('ativo', models.BooleanField(default=True, help_text='Empresa ativa no sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Técnico disponível para atender chamados'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o usuário pertence (obrigatório para terceiros)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
    ]
