# Generated by Django 5.1.4 on 2025-12-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_empresa_perfilusuario_disponivel_and_more'),
        ('frota_locada', '0010_chamadomanutencao_foto_problema'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fornecedor',
            field=models.OneToOneField(blank=True, help_text='Fornecedor correspondente no módulo de frota locada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_vinculada', to='frota_locada.fornecedor'),
        ),
    ]
