# Generated by Django 5.1.4 on 2025-12-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_empresa_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='fornecedor',
        ),
    ]
