# Generated by refatoração PERFIL_CHOICES -> TipoPerfil

from django.db import migrations, models


def migrar_perfis_existentes(apps, schema_editor):
    """Migra os perfis hardcoded para a tabela TipoPerfil"""
    TipoPerfil = apps.get_model('core', 'TipoPerfil')
    
    # Perfis existentes no PERFIL_CHOICES
    perfis_padrao = [
        # (codigo, nome, descricao, is_admin, is_supervisor, is_terceiro)
        ('ADMIN', 'Administrador', 
         'Acesso total ao sistema. Pode gerenciar usuários, perfis, empresas e todas as funcionalidades.', 
         True, False, False),
        
        ('SUPERVISOR', 'Supervisor', 
         'Supervisiona operações. Pode gerenciar pedidos, visualizar relatórios e aprovar solicitações.', 
         False, True, False),
        
        ('DEMANDANTE', 'Demandante', 
         'Pode criar e acompanhar pedidos de serviços e transportes.', 
         False, False, False),
        
        ('TRANSPORTES', 'Setor de Transportes', 
         'Responsável por operações de transporte e movimentação de equipamentos.', 
         False, False, False),
        
        # Manutenção interna por especialidade
        ('MANUTENCAO_PTA', 'Manutenção - PTA (Ponte de Transferência)', 
         'Responsável por manutenção de PTAs (Pontes de Transferência).', 
         False, False, False),
        
        ('MANUTENCAO_EMPILHADEIRA', 'Manutenção - Empilhadeiras', 
         'Responsável por manutenção de empilhadeiras.', 
         False, False, False),
        
        ('MANUTENCAO_GUINDASTE', 'Manutenção - Guindastes', 
         'Responsável por manutenção de guindastes.', 
         False, False, False),
        
        ('MANUTENCAO_SOLDA', 'Manutenção - Equipamentos de Solda', 
         'Responsável por manutenção de equipamentos de solda.', 
         False, False, False),
        
        ('MANUTENCAO_GERAL', 'Manutenção - Equipamentos Gerais', 
         'Responsável por manutenção geral de equipamentos.', 
         False, False, False),
        
        # Terceiros credenciados por especialidade
        ('TERCEIRO_MANUTENCAO_PTA', 'Terceiro - Manutenção PTA', 
         'Prestador de serviços terceirizado para manutenção de PTAs.', 
         False, False, True),
        
        ('TERCEIRO_MANUTENCAO_EMPILHADEIRA', 'Terceiro - Manutenção Empilhadeiras', 
         'Prestador de serviços terceirizado para manutenção de empilhadeiras.', 
         False, False, True),
        
        ('TERCEIRO_MANUTENCAO_GUINDASTE', 'Terceiro - Manutenção Guindastes', 
         'Prestador de serviços terceirizado para manutenção de guindastes.', 
         False, False, True),
        
        ('TERCEIRO_MANUTENCAO_SOLDA', 'Terceiro - Manutenção Solda', 
         'Prestador de serviços terceirizado para manutenção de equipamentos de solda.', 
         False, False, True),
        
        ('TERCEIRO_MANUTENCAO_GERAL', 'Terceiro - Manutenção Geral', 
         'Prestador de serviços terceirizado para manutenção geral.', 
         False, False, True),
        
        # Manutenção genérica (compatibilidade)
        ('MANUTENCAO', 'Manutenção (Genérica)', 
         'Perfil genérico de manutenção para compatibilidade com versões anteriores.', 
         False, False, False),
    ]
    
    for codigo, nome, descricao, is_admin, is_supervisor, is_terceiro in perfis_padrao:
        TipoPerfil.objects.create(
            codigo=codigo,
            nome=nome,
            descricao=descricao,
            is_admin=is_admin,
            is_supervisor=is_supervisor,
            is_terceiro=is_terceiro,
            ativo=True,
            is_sistema=True  # Marca como perfil do sistema (não pode ser excluído)
        )
    
    print(f"✅ {len(perfis_padrao)} perfis migrados para TipoPerfil")


def reverter_migracao(apps, schema_editor):
    """Reverte a migração removendo todos os TipoPerfil"""
    TipoPerfil = apps.get_model('core', 'TipoPerfil')
    TipoPerfil.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_empresa_fornecedor'),
    ]

    operations = [
        # 1. Criar tabela TipoPerfil
        migrations.CreateModel(
            name='TipoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do perfil (ex: ADMIN, SUPERVISOR)', max_length=50, unique=True)),
                ('nome', models.CharField(help_text='Nome do perfil', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do perfil e suas permissões')),
                ('permissoes_resumo', models.TextField(blank=True, help_text='Resumo das permissões do perfil')),
                ('is_admin', models.BooleanField(default=False, help_text='Perfil tem privilégios de administrador')),
                ('is_supervisor', models.BooleanField(default=False, help_text='Perfil tem privilégios de supervisor')),
                ('is_terceiro', models.BooleanField(default=False, help_text='Perfil é de terceiro (requer empresa vinculada)')),
                ('ativo', models.BooleanField(default=True, help_text='Perfil está ativo e disponível para uso')),
                ('is_sistema', models.BooleanField(default=False, help_text='Perfil do sistema (não pode ser excluído pelo usuário)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Perfil',
                'verbose_name_plural': 'Tipos de Perfis',
                'ordering': ['nome'],
            },
        ),
        
        # 2. Migrar dados existentes
        migrations.RunPython(migrar_perfis_existentes, reverter_migracao),
    ]

