# Generated by refatoração PERFIL_CHOICES -> TipoPerfil

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_criar_tipo_perfil'),
    ]

    operations = [
        # Adicionar campo tipo_perfil (nullable temporariamente)
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_perfil',
            field=models.ForeignKey(
                blank=True,
                help_text='Tipo de perfil do usuário',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='perfilusuario_set',
                to='core.tipoperfil'
            ),
        ),
    ]

