# Generated by refatoração PERFIL_CHOICES -> TipoPerfil

from django.db import migrations


def migrar_usuarios_para_tipo_perfil(apps, schema_editor):
    """Migra todos os usuários de perfil (CharField) para tipo_perfil (ForeignKey)"""
    PerfilUsuario = apps.get_model('core', 'PerfilUsuario')
    TipoPerfil = apps.get_model('core', 'TipoPerfil')
    
    usuarios_migrados = 0
    usuarios_com_erro = []
    
    for perfil_usuario in PerfilUsuario.objects.all():
        try:
            # Buscar o TipoPerfil correspondente ao código do perfil antigo
            tipo = TipoPerfil.objects.get(codigo=perfil_usuario.perfil)
            perfil_usuario.tipo_perfil = tipo
            perfil_usuario.save()
            usuarios_migrados += 1
        except TipoPerfil.DoesNotExist:
            usuarios_com_erro.append({
                'id': perfil_usuario.id,
                'username': perfil_usuario.user.username,
                'perfil_antigo': perfil_usuario.perfil
            })
    
    print(f"✅ {usuarios_migrados} usuários migrados para tipo_perfil")
    
    if usuarios_com_erro:
        print(f"⚠️ {len(usuarios_com_erro)} usuários com erro:")
        for erro in usuarios_com_erro:
            print(f"   - ID {erro['id']}: {erro['username']} (perfil: {erro['perfil_antigo']})")


def reverter_migracao(apps, schema_editor):
    """Reverte a migração limpando tipo_perfil"""
    PerfilUsuario = apps.get_model('core', 'PerfilUsuario')
    PerfilUsuario.objects.all().update(tipo_perfil=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_adicionar_tipo_perfil_em_perfilusuario'),
    ]

    operations = [
        migrations.RunPython(migrar_usuarios_para_tipo_perfil, reverter_migracao),
    ]

