# Generated by refatoração PERFIL_CHOICES -> TipoPerfil

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_migrar_dados_perfil_para_tipo_perfil'),
    ]

    operations = [
        # 1. Tornar tipo_perfil obrigatório (NOT NULL)
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_perfil',
            field=models.ForeignKey(
                help_text='Tipo de perfil do usuário',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='perfilusuario_set',
                to='core.tipoperfil'
            ),
        ),
        
        # 2. Remover campo perfil antigo (CharField)
        migrations.RemoveField(
            model_name='perfilusuario',
            name='perfil',
        ),
    ]

