# Generated by refatoração PERFIL_CHOICES -> TipoPerfil

from django.db import migrations


def migrar_descricoes_personalizadas(apps, schema_editor):
    """Migra descrições personalizadas de DescricaoPerfil para TipoPerfil"""
    DescricaoPerfil = apps.get_model('core', 'DescricaoPerfil')
    TipoPerfil = apps.get_model('core', 'TipoPerfil')
    
    migrados = 0
    
    for descricao in DescricaoPerfil.objects.all():
        try:
            tipo = TipoPerfil.objects.get(codigo=descricao.codigo_perfil)
            
            # Atualizar com dados personalizados se existirem
            if descricao.nome_personalizado:
                tipo.nome = descricao.nome_personalizado
            
            if descricao.descricao:
                tipo.descricao = descricao.descricao
            
            if descricao.permissoes_resumo:
                tipo.permissoes_resumo = descricao.permissoes_resumo
            
            tipo.ativo = descricao.ativo
            tipo.save()
            migrados += 1
            
        except TipoPerfil.DoesNotExist:
            print(f"⚠️ TipoPerfil não encontrado para código: {descricao.codigo_perfil}")
    
    print(f"✅ {migrados} descrições personalizadas migradas para TipoPerfil")


def reverter_migracao(apps, schema_editor):
    """Não há reversão - dados já foram migrados"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_tornar_tipo_perfil_obrigatorio'),
    ]

    operations = [
        # 1. Migrar descrições personalizadas antes de deletar
        migrations.RunPython(migrar_descricoes_personalizadas, reverter_migracao),
        
        # 2. Deletar modelo DescricaoPerfil
        migrations.DeleteModel(
            name='DescricaoPerfil',
        ),
    ]

