# Generated by Django 4.2.16 on 2026-02-09 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_adicionar_perfis_controle_pta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_agendamento',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data para execução do serviço. Padrão: hoje'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto_material',
            field=models.ImageField(blank=True, help_text='Foto do material a ser transportado (opcional)', null=True, upload_to='materiais/'),
        ),
    ]
