# Generated by Django 4.2.16 on 2026-02-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_foto_material_e_data_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora_agendamento',
            field=models.TimeField(blank=True, help_text='Hora desejada para execução do serviço (opcional)', null=True),
        ),
    ]
