# Generated by Django 5.1.4 on 2025-11-24 16:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Fornecedor')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX')], verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('contato_responsavel', models.CharField(blank=True, max_length=100, verbose_name='Contato Responsável')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Manutenção')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Manutenção',
                'verbose_name_plural': 'Tipos de Manutenção',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Veículo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Veículo',
                'verbose_name_plural': 'Tipos de Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VeiculoLocado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}-?\\d{4}$|^[A-Z]{3}\\d[A-Z]\\d{2}$', 'Placa deve estar no formato ABC-1234 ou ABC1D23')], verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('numero_contrato', models.CharField(blank=True, max_length=50, verbose_name='Número do Contrato')),
                ('data_inicio_locacao', models.DateField(verbose_name='Data de Início da Locação')),
                ('data_fim_locacao', models.DateField(blank=True, null=True, verbose_name='Data de Fim da Locação')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal (R$)')),
                ('valor_km', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Valor por KM (R$)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo'), ('DEVOLVIDO', 'Devolvido')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('km_inicial', models.IntegerField(default=0, verbose_name='KM Inicial')),
                ('km_atual', models.IntegerField(default=0, verbose_name='KM Atual')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota_locada.fornecedor', verbose_name='Fornecedor')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota_locada.tipoveiculo', verbose_name='Tipo de Veículo')),
            ],
            options={
                'verbose_name': 'Veículo Locado',
                'verbose_name_plural': 'Veículos Locados',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ManutencaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(verbose_name='Data de Agendamento')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('oficina', models.CharField(blank=True, max_length=200, verbose_name='Oficina/Prestador')),
                ('km_veiculo', models.IntegerField(verbose_name='KM do Veículo')),
                ('valor_orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Orçamento (R$)')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final (R$)')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('tipo_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota_locada.tipomanutencao', verbose_name='Tipo de Manutenção')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='frota_locada.veiculolocado', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Manutenção de Veículo',
                'verbose_name_plural': 'Manutenções de Veículos',
                'ordering': ['-data_agendamento'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_anterior', models.IntegerField(verbose_name='KM Anterior')),
                ('km_atual', models.IntegerField(verbose_name='KM Atual')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_km', to='frota_locada.veiculolocado', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Histórico de KM',
                'verbose_name_plural': 'Histórico de KM',
                'ordering': ['-data_registro'],
            },
        ),
    ]
