# Generated by Django 5.1.4 on 2025-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0001_initial'),
    ]

    operations = [
        # Apenas criar o modelo MarcaVeiculo
        migrations.CreateModel(
            name='MarcaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Marca de Veículo',
                'verbose_name_plural': 'Marcas de Veículos',
                'ordering': ['nome'],
            },
        ),
    ]
