# Generated by Django 5.1.4 on 2025-11-24 17:30

import django.db.models.deletion
from django.db import migrations, models


def migrate_marca_data(apps, schema_editor):
    """Migra dados existentes do campo marca (CharField) para MarcaVeiculo"""
    VeiculoLocado = apps.get_model('frota_locada', 'VeiculoLocado')
    MarcaVeiculo = apps.get_model('frota_locada', 'MarcaVeiculo')
    
    # Para cada veículo existente, criar ou buscar a marca correspondente
    for veiculo in VeiculoLocado.objects.all():
        if veiculo.marca:  # Se o campo marca não estiver vazio
            marca_obj, created = MarcaVeiculo.objects.get_or_create(
                nome=veiculo.marca.strip().title(),
                defaults={'ativo': True}
            )
            # Atualizar o campo marca_temp com a referência ao objeto MarcaVeiculo
            veiculo.marca_temp = marca_obj
            veiculo.save()


def reverse_migrate_marca_data(apps, schema_editor):
    """Reverte a migração copiando dados de volta para CharField"""
    VeiculoLocado = apps.get_model('frota_locada', 'VeiculoLocado')
    
    # Para cada veículo, copiar o nome da marca de volta para o campo CharField
    for veiculo in VeiculoLocado.objects.all():
        if veiculo.marca_temp:
            veiculo.marca = veiculo.marca_temp.nome
            veiculo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0002_marcaveiculo_alter_veiculolocado_marca'),
    ]

    operations = [
        # Adicionar campo temporário para a nova marca
        migrations.AddField(
            model_name='veiculolocado',
            name='marca_temp',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='frota_locada.marcaveiculo', verbose_name='Marca Temp'),
        ),
        
        # Migrar dados existentes
        migrations.RunPython(migrate_marca_data, reverse_migrate_marca_data),
        
        # Remover o campo marca antigo
        migrations.RemoveField(
            model_name='veiculolocado',
            name='marca',
        ),
        
        # Renomear o campo temporário para marca
        migrations.RenameField(
            model_name='veiculolocado',
            old_name='marca_temp',
            new_name='marca',
        ),
        
        # Alterar o campo para não permitir null
        migrations.AlterField(
            model_name='veiculolocado',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota_locada.marcaveiculo', verbose_name='Marca'),
        ),
    ]
