# Generated by Django 5.1.4 on 2025-11-25 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0003_alter_veiculolocado_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Máquina')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('GUINDASTE', 'Guindaste'), ('SOLDA', 'Equipamento de Solda'), ('CORTE', 'Equipamento de Corte'), ('COMPRESSOR', 'Compressor'), ('GERADOR', 'Gerador'), ('BOMBA', 'Bomba'), ('EMPILHADEIRA', 'Empilhadeira'), ('PONTE_ROLANTE', 'Ponte Rolante'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
                ('setor', models.CharField(blank=True, max_length=50, verbose_name='Setor')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=50, verbose_name='Número de Série')),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chamado', models.CharField(max_length=20, unique=True, verbose_name='Número do Chamado')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('tipo_problema', models.CharField(choices=[('ELETRICO', 'Elétrico'), ('MECANICO', 'Mecânico'), ('HIDRAULICO', 'Hidráulico'), ('PNEUMATICO', 'Pneumático'), ('SOFTWARE', 'Software'), ('ESTRUTURAL', 'Estrutural'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo do Problema')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('data_inicio_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início do Atendimento')),
                ('data_fim_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim do Atendimento')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Atendimento'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('PAUSADO', 'Pausado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20, verbose_name='Status')),
                ('descricao_solucao', models.TextField(blank=True, verbose_name='Descrição da Solução')),
                ('pecas_utilizadas', models.TextField(blank=True, verbose_name='Peças Utilizadas')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Mecânico')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='frota_locada.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Chamado de Manutenção',
                'verbose_name_plural': 'Chamados de Manutenção',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
