# Generated by Django 5.1.4 on 2025-11-25 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0004_maquina_chamadomanutencao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculolocado',
            name='km_atual',
        ),
        migrations.RemoveField(
            model_name='veiculolocado',
            name='km_inicial',
        ),
        migrations.RemoveField(
            model_name='veiculolocado',
            name='valor_km',
        ),
        migrations.AddField(
            model_name='veiculolocado',
            name='horimetro_atual',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Horímetro Atual (h)'),
        ),
        migrations.AddField(
            model_name='veiculolocado',
            name='horimetro_inicial',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Horímetro Inicial (h)'),
        ),
        migrations.CreateModel(
            name='HistoricoHorimetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horimetro_anterior', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Horímetro Anterior (h)')),
                ('horimetro_atual', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Horímetro Atual (h)')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_horimetro', to='frota_locada.veiculolocado', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Histórico de Horímetro',
                'verbose_name_plural': 'Histórico de Horímetro',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.DeleteModel(
            name='HistoricoKm',
        ),
    ]
