# Generated by Django 5.1.4 on 2025-11-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0005_remove_veiculolocado_km_atual_and_more'),
    ]

    operations = [
    ]
