# Generated by Django 5.1.4 on 2025-11-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0006_auto_20251125_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculolocado',
            name='locado_para',
            field=models.CharField(choices=[('PRODUCAO', 'Produção'), ('MANUTENCAO', 'Manutenção'), ('ADMINISTRATIVO', 'Administrativo')], default='PRODUCAO', help_text='Setor para o qual o veículo está locado', max_length=20, verbose_name='Locado Para'),
        ),
        migrations.AlterField(
            model_name='veiculolocado',
            name='horimetro_atual',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Horímetro atual do veículo', max_digits=10, verbose_name='Horímetro Atual'),
        ),
        migrations.AlterField(
            model_name='veiculolocado',
            name='horimetro_inicial',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Horímetro do veículo no início da locação', max_digits=10, verbose_name='Horímetro Inicial'),
        ),
    ]
