# Generated by Django 4.2.16 on 2025-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0007_veiculolocado_locado_para_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculolocado',
            name='data_fim_locacao',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão Fim Locação'),
        ),
        migrations.AlterField(
            model_name='veiculolocado',
            name='placa',
            field=models.CharField(help_text='Código de identificação do equipamento (ex: ABC-1234, ABC1D23, EQ001, etc.)', max_length=20, unique=True, verbose_name='Placa/Código'),
        ),
    ]
