# Generated by Django 4.2.16 on 2025-11-27 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frota_locada', '0008_alter_veiculolocado_data_fim_locacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frota_locada.fornecedor', verbose_name='Fornecedor Responsável'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MecanicoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_vinculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Vínculo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota_locada.fornecedor', verbose_name='Fornecedor')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mecânico')),
            ],
            options={
                'verbose_name': 'Mecânico do Fornecedor',
                'verbose_name_plural': 'Mecânicos dos Fornecedores',
                'unique_together': {('fornecedor', 'mecanico')},
            },
        ),
    ]
