# Generated by Django 4.2.16 on 2025-11-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0009_maquina_fornecedor_mecanicofornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadomanutencao',
            name='foto_problema',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/fotos/', verbose_name='Foto do Problema'),
        ),
    ]
