# Generated by Django 5.1.4 on 2025-12-04 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_empresa_fornecedor'),
        ('frota_locada', '0010_chamadomanutencao_foto_problema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='maquina',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='Empresa proprietária ou locadora do equipamento', on_delete=django.db.models.deletion.PROTECT, to='core.empresa', verbose_name='Empresa Responsável'),
            preserve_default=False,
        ),
    ]
