# Generated by Django 5.1.4 on 2025-12-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0011_remove_maquina_fornecedor_maquina_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MecanicoFornecedor',
        ),
    ]
