# Generated by Django 5.1.4 on 2025-12-08 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0012_remove_mecanico_fornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Início')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Finalização')),
                ('tipo_manutencao', models.CharField(choices=[('MECANICA', 'Manutenção Mecânica'), ('ELETRICA', 'Manutenção Elétrica'), ('HIDRAULICA', 'Manutenção Hidráulica'), ('PNEUMATICA', 'Manutenção Pneumática'), ('PREVENTIVA', 'Manutenção Preventiva'), ('CORRETIVA', 'Manutenção Corretiva'), ('PREDITIVA', 'Manutenção Preditiva'), ('LUBRIFICACAO', 'Lubrificação'), ('LIMPEZA', 'Limpeza'), ('AJUSTE', 'Ajuste/Calibração'), ('TROCA_PNEU', 'Troca/Reparo de Pneu'), ('SOLDAGEM', 'Soldagem'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Manutenção')),
                ('descricao_servico', models.TextField(help_text='Descreva detalhadamente o que foi feito', verbose_name='Descrição do Serviço Realizado')),
                ('pecas_trocadas', models.TextField(blank=True, help_text='Liste as peças trocadas ou utilizadas (uma por linha)', verbose_name='Peças Trocadas/Utilizadas')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o atendimento', verbose_name='Observações')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status do Atendimento')),
                ('tempo_atendimento', models.DurationField(blank=True, help_text='Calculado automaticamente ao finalizar', null=True, verbose_name='Tempo de Atendimento')),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='atendimentos/fotos/antes/', verbose_name='Foto Antes do Reparo')),
                ('foto_depois', models.ImageField(blank=True, null=True, upload_to='atendimentos/fotos/depois/', verbose_name='Foto Depois do Reparo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='frota_locada.chamadomanutencao', verbose_name='Chamado')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Mecânico Responsável')),
            ],
            options={
                'verbose_name': 'Atendimento de Chamado',
                'verbose_name_plural': 'Atendimentos de Chamados',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
