# Generated by Django 5.1.4 on 2025-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0013_atendimentochamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentochamado',
            name='descricao_servico',
            field=models.TextField(blank=True, help_text='Descreva detalhadamente o que foi feito', verbose_name='Descrição do Serviço Realizado'),
        ),
    ]
