# Generated by Django 5.1.4 on 2025-12-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0014_alter_atendimentochamado_descricao_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentochamado',
            name='mau_uso',
            field=models.BooleanField(default=False, help_text='Marque se a falha foi causada por mau uso do equipamento pelo usuário', verbose_name='Mau Uso do Equipamento'),
        ),
    ]
