# Generated by Django 5.1.4 on 2025-12-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0015_atendimentochamado_mau_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadomanutencao',
            name='veiculo_locado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='frota_locada.veiculolocado', verbose_name='Veículo/Equipamento Locado'),
        ),
        migrations.AlterField(
            model_name='chamadomanutencao',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='frota_locada.maquina', verbose_name='Máquina'),
        ),
    ]
