# Generated by Django 4.2.16 on 2025-12-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0016_chamadomanutencao_veiculo_locado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(choices=[('PTA', 'PTA (Plataforma de Trabalho Aéreo)'), ('GUINDASTE', 'Guindaste'), ('EMPILHADEIRA', 'Empilhadeira'), ('CAMINHAO', 'Caminhão'), ('PICKUP', 'Pickup'), ('SOLDA', 'Equipamento de Solda'), ('CORTE', 'Equipamento de Corte'), ('COMPRESSOR', 'Compressor'), ('GERADOR', 'Gerador'), ('BOMBA', 'Bomba'), ('PONTE_ROLANTE', 'Ponte Rolante'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo'),
        ),
    ]
