# Generated by Django 4.2.16 on 2025-12-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota_locada', '0017_alter_maquina_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadomanutencao',
            name='tipo_equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='frota_locada.tipoveiculo', verbose_name='Tipo de Equipamento'),
        ),
    ]
