# Generated by Django 4.2.16 on 2025-12-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_adicionar_perfis_controle_pta'),
        ('frota_locada', '0019_fornecedor_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa que presta serviço de manutenção para os equipamentos deste fornecedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_atendidos', to='core.empresa', verbose_name='Empresa Responsável pela Manutenção'),
        ),
    ]
