# Generated by Django 5.1.4 on 2025-10-16 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gas', models.CharField(max_length=100, unique=True, verbose_name='Nome do Gás')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Gás',
                'verbose_name_plural': 'Tipos de Gases',
                'ordering': ['nome_gas'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('nf', models.CharField(max_length=50, verbose_name='Nota Fiscal')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(choices=[('KG', 'Quilograma (KG)'), ('M3', 'Metro Cúbico (M³)')], max_length=3, verbose_name='Unidade')),
                ('embalagem', models.CharField(choices=[('CILINDROS', 'Cilindros'), ('CESTA', 'Cesta'), ('A_GRANEL', 'A Granel'), ('LIQUIDO', 'Líquido')], max_length=20, verbose_name='Embalagem')),
                ('fornecedor', models.CharField(choices=[('WHITE_MARTINS', 'White Martins'), ('ULTRA_GAS', 'Ultra Gas')], max_length=20, verbose_name='Fornecedor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tipo_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gases.tipogas', verbose_name='Tipo de Gás')),
            ],
            options={
                'verbose_name': 'Movimentação de Gás',
                'verbose_name_plural': 'Movimentações de Gases',
                'ordering': ['-data_entrega', '-criado_em'],
            },
        ),
    ]
