# Generated by Django 5.1.4 on 2025-10-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_equipamento_quantidade_litros_and_more'),
        ('gases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaogas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='movimentacaogas',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='movimentacaogas',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Unitário'),
        ),
    ]
