# Generated by Django 5.1.4 on 2025-10-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gases', '0002_movimentacaogas_cliente_movimentacaogas_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaogas',
            name='embalagem',
            field=models.CharField(choices=[('ACETILENO_CILINDRO', 'Acetileno/Cilindro'), ('ARGONIO_CILINDRO', 'Argônio/Cilindro'), ('DIOXIDO_CARBONO_CILINDRO', 'Dioxido Carbono/Cilindro'), ('DIOXIDO_CARBONO_LIQUIDO', 'Dioxido Carbono/Líquido'), ('GLP_GRANEL', 'GLP granel'), ('NITROGENIO_CILINDRO', 'Nitrogênio/Cilindro'), ('OXIGENIO_MEDICINAL_CILINDRO', 'Oxigênio Medicinal/Cilindro'), ('OXIGENIO_CILINDRO', 'Oxigênio/Cilindro'), ('OXIGENIO_LIQUIDO', 'Oxigênio/Líquido')], max_length=50, verbose_name='Embalagem'),
        ),
    ]
