# Generated by Django 5.1.4 on 2025-10-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gases', '0003_alter_movimentacaogas_embalagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaogas',
            name='embalagem',
            field=models.CharField(choices=[('ACETILENO_CILINDRO', 'Acetileno/Cilindro'), ('ARGONIO_CILINDRO', 'Argônio/Cilindro'), ('DIOXIDO_CARBONO', 'Dioxido Carbono'), ('GLP_GRANEL', 'GLP granel'), ('NITROGENIO_CILINDRO', 'Nitrogênio/Cilindro'), ('OXIGENIO_MEDICINAL_CILINDRO', 'Oxigênio Medicinal/Cilindro'), ('OXIGENIO', 'Oxigênio')], max_length=50, verbose_name='Embalagem'),
        ),
    ]
