# Generated by Django 5.1.4 on 2025-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gases', '0004_alter_movimentacaogas_embalagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaogas',
            name='embalagem',
            field=models.CharField(choices=[('ACETILENO', 'Acetileno'), ('ARGONIO', 'Argônio'), ('DIOXIDO_CARBONO', 'Dioxido Carbono'), ('GLP', 'GLP'), ('NITROGENIO', 'Nitrogênio'), ('OXIGENIO_MEDICINAL', 'Oxigênio Medicinal'), ('OXIGENIO', 'Oxigênio')], max_length=50, verbose_name='Embalagem'),
        ),
    ]
