# Generated by Django 5.1.4 on 2025-10-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gases', '0005_alter_movimentacaogas_embalagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaogas',
            name='embalagem',
        ),
        migrations.AddField(
            model_name='movimentacaogas',
            name='categoria_gas',
            field=models.CharField(choices=[('ACETILENO', 'Acetileno'), ('ARGONIO', 'Argônio'), ('DIOXIDO_CARBONO', 'Dioxido Carbono'), ('GLP', 'GLP'), ('NITROGENIO', 'Nitrogênio'), ('OXIGENIO_MEDICINAL', 'Oxigênio Medicinal'), ('OXIGENIO', 'Oxigênio')], default=1, max_length=50, verbose_name='Categoria do Gás'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacaogas',
            name='fornecedor',
            field=models.CharField(choices=[('WHITE_MARTINS', 'White Martins'), ('ULTRA_GAS', 'Ultra Gas'), ('ULTRAGAZ_BAHIANA', 'Ultragaz/Bahiana')], max_length=20, verbose_name='Fornecedor'),
        ),
    ]
